language: python

sudo: false

python: 
  - "3.6"

dist: trusty

git:
  depth: 1

install:
  - pip3 install -r requirements.txt

env: 
  - TRAVIS_SECURE_ENV_VARS=true

script:
  - coverage run manage.py test 

after_success:
  - codecov