language: python

python: 
  - "3.6^"

git:
  depth: 1

install:
  - pip3 install -r requirements.txt

env: 
  - TRAVIS_SECURE_ENV_VARS=true

script:
  - python manage.py makemigrations
  - python manage.py migrate