language: python

python: 
  - "3.6.0"

git:
  depth: 1

install:
  - pip3 install -r requirements.txt

env: 
  - TRAVIS_SECURE_ENV_VARS=true

script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate