language: python

python: 
  - "3.6"

git:
  depth: 1

install:
  - pip3 install -r requirements.txt
  - pip3 install codecov

env: 
  - TRAVIS_SECURE_ENV_VARS=true

script:
  - coverage run manage.py test backend

after_success:
  - codecov