# Generated by Django 2.1.1 on 2018-11-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prouductName', models.CharField(max_length=100)),
                ('datails', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('prices', models.CharField(max_length=10)),
            ],
        ),
    ]
