# Generated by Django 2.1.1 on 2018-11-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backend',
            old_name='datails',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='backend',
            old_name='prouductName',
            new_name='productName',
        ),
    ]
