# Generated by Django 2.1.1 on 2018-11-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('prices', models.CharField(max_length=10)),
            ],
        ),
    ]
